### ISSUE TITLE
利用partial fc 训练的mobilefacenet转mxnet格式模型报错

### ISSUE THREAD

**Issue by TJXTT** [Oneflow-Inc/oneflow_face#11]
Oneflow开发组你们好:
             我训练了基于partial fc 的mobilefacenet模型, 想转换为mxnet格式, 但运行 ./tools/model_convert/mobilefacenet/of_model_2_mxnet_model.py 出现了错误.

执行的脚本为:

python of_model_2_mxnet_model.py --mxnet_load_prefix='./model-y1-test2/model' --mxnet_load_epoch=0 --mxnet_save_prefix='./mxnet_save' --mxnet_save_epoch=1 --of_model_dir='./snapshot_30/'

报错为:

[22:11:10] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.0.0. Attempting to upgrade...
[22:11:10] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!

fc1_gamma gamma error
Traceback (most recent call last):
  File "of_model_2_mxnet_model.py", line 88, in <module>
    of_model_path + "-weight/out", dtype=np.float32
FileNotFoundError: [Errno 2] No such file or directory: './snapshot_30/fc1-weight/out'

查看了snapshot_30目录下生成的文件, 并未发现fc1-weight文件夹

**Comment by Flowingsun007** [comment]
请先查看一下模型保存是否完整（snapshot_30之前的模型是否存在fc1-weight文件夹），我们也将尽快检查模型转化脚本的正确性，感谢您的反馈！

**Comment by TJXTT** [comment]
已检查, snapshot_30之前保存的模型文件中不存在fc1-weight文件夹. 此外, 上述脚本的参数  --mxnet_load_prefix 加载的是insightface提供的预训练模型, 下载地址在 https://pan.baidu.com/s/1If28BkHde4fiuweJrbicVA

**Comment by guo-ran** [comment]
可以看一下应该有pre_fc1-weight这个模型文件夹，和你用的这个预训练模型中的fc1-weight是对应的，可以把oneflow保存的模型中的pre_fc1-weight文件夹改名为fc1-weight，再转换试一下。
我们做转换脚本时mxnet模型对应的层保存的模型是pre_fc1_weight，我们会尽快检查最新的提供的预训练模型并修改转换脚本。

**Comment by TJXTT** [comment]
感谢您的帮助, 目前改用Insightface最新版本的代码生成的mxnet模型代替上述的预训练模型后，已成功地进行了转换。

**Comment by yuanms2** [comment]
> 代替

您说的insightface最新版本代码是指insightface 中的oneflow_face 代码吗？

**Comment by TJXTT** [comment]
> 您说的insightface最新版本代码是指insightface 中的oneflow_face 代码吗？


是insightface/recognition/Arcface下的训练代码 :)
