### ISSUE TITLE
数据转化和切分

### ISSUE THREAD

**Issue by wwt0805** [Oneflow-Inc/oneflow_face#5]
OF开发团队你们好：
我们最近在使用仓库代码的过程中发现了些问题。主要是运行mx_recordio_2_ofrecord.py的时间过长，而且仓库中也没有提供在多机多卡情况下的模型切分程序，虽然我们自行完成了切分功能，但是仓库提供的代码确实有所缺失。再细说一下数据切分的问题。理论上OF要求训练数据份数必须是gpu总个数的整数倍，在之前的分布式测试中我们一直使用的是3节点每节点5gpu也就是总共15卡进行训练，所以相应的数据切分也是15份。但是在实际的使用过程中会涉及到资源分配的问题，无法保证每次训练的确切gpu总数，可能这次是单机4卡，下次是3机18卡。有一种折中方案就是公约数较多的样本份数，比如90，可以满足gpu个数1、2、3、6、9、10、15、18、30、45、90等等情况。但是仍然不能满足所有条件，依然没有普遍性。
所以，想提出两点：
1、能否加快格式转化和切分过程
2、能否统一转化和切分程序或脚本

谢谢！

**Comment by wwt0805** [comment]
这两天自己写了一个多线程的，facesemore数据集的转化和切分。写的比较水，大家一起修改。


import os
import sys
import time
import struct
import argparse
from multiprocessing import Process

from mxnet import recordio
import oneflow.core.record.record_pb2 as of_record


class ConvertSplit:
    def __init__(self, data_dir='/home/DLP/wwt/InsightFace/oneflow_face-master/faces_emore',
                 output_filepath='./output', cut_num=1):
        self.data_dir = data_dir
        self.output_filepath = output_filepath
        self.cut_num = cut_num

    def load_train_data(self, data_dir):
        path_imgrec = os.path.join(data_dir, 'train.rec')
        path_imgidx = path_imgrec[0:-4] + '.idx'
        imgrec = recordio.MXIndexedRecordIO(path_imgidx, path_imgrec, "r", key_type=int)

        id2range = dict()
        rec0 = imgrec.read_idx(0)
        header0, img_str = recordio.unpack(rec0)

        if header0.flag > 0:
            identity_key_start = int(header0.label[0])
            identity_key_end = int(header0.label[1])
            imgidx_list = range(1, identity_key_start)

            # Read identity id range
            for identity in range(identity_key_start, identity_key_end):
                rec = imgrec.read_idx(identity)
                header, s = recordio.unpack(rec)
                a, b = int(header.label[0]), int(header.label[1])
                id2range[identity] = (a, b)

        else:
            imgidx_list = imgrec.keys

        # print(len(imgidx_list))

        return imgrec, imgidx_list

    def convert_to_ofrecord(self, img_data):
        """ Convert python dictionary formath data of one image to of.Example proto.
      Args:
        img_data: Python dict.
      Returns:
        example: The converted of.Exampl
      """

        def _int32_feature(value):
            """Wrapper for inserting int32 features into Example proto."""
            if not isinstance(value, list):
                value = [value]
            return of_record.Feature(int32_list=of_record.Int32List(value=value))

        def _float_feature(value):
            """Wrapper for inserting float features into Example proto."""
            if not isinstance(value, list):
                value = [value]
            return of_record.Feature(float_list=of_record.FloatList(value=value))

        def _double_feature(value):
            """Wrapper for inserting float features into Example proto."""
            if not isinstance(value, list):
                value = [value]
            return of_record.Feature(double_list=of_record.DoubleList(value=value))

        def _bytes_feature(value):
            """Wrapper for inserting bytes features into Example proto."""
            # if isinstance(value, six.string_types):
            #  value = six.binary_type(value, encoding='utf-8')
            return of_record.Feature(bytes_list=of_record.BytesList(value=[value]))

        example = of_record.OFRecord(
            feature={
                "label": _int32_feature(img_data["label"]),
                "encoded": _bytes_feature(img_data["pixel_data"]),
            }
        )

        return example

    def split(self):
        try:
            os.system('rm -rf {}'.format(self.output_filepath))
            print('remove finished')
        except:
            print('remove failed')
        imgrec, imgidx_list = self.load_train_data(data_dir=self.data_dir)
        output_dir = os.path.join(self.output_filepath, 'train')
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
        length = len(imgidx_list)
        average = int(length / self.cut_num)
        idx_list = list()

        for i in range(1, self.cut_num + 1):
            for idx in imgidx_list:
                if idx % average == 0:
                    idx = i * idx
                    idx_list.append(idx)
                    break

        if idx_list[-1] != length:
            idx_list[-1] = length
        idx_list.insert(0, 1)

        return idx_list

    def convert1(self, name, split_begin, split_end):
        print("thread {} start ".format(name))
        imgrec, imgidx_list = self.load_train_data(self.data_dir)
        output_dir = os.path.join(self.output_filepath, 'train')
        idx_list = self.split()
        # print('idx_list in convert:{}'.format(idx_list))
        # [1, 582265, 1164530, 1746795, 2329060, 2911325, 3493590, 4075855, 4658120, 5240385, 5822653]

        for i in range(split_begin, split_end):
            file_path = 'part-000' + format(str(i), '0>2s')
            output_file = os.path.join(output_dir, file_path)
            with open(output_file, 'wb') as f:
                list_idx = [j for j in range(idx_list[i], idx_list[i + 1])]
                # print(file_path + " start: " + str(len(list_idx)))
                # print(file_path + ' start index: ' + str((list_idx[i])))
                # print('number of samples in this part:' + str(len(list_idx)))
                print('{} start index: {} -- number of samples in this part: {}'.format(file_path, list_idx[i], len(list_idx)))
                print('splitting and converting, please wait for a while!')
                print('='*75)
                start = time.time()
                for idx in list_idx:
                    img_data = {}
                    rec = imgrec.read_idx(idx)
                    header, s = recordio.unpack(rec)
                    img_data["label"] = int(header.label)
                    img_data["pixel_data"] = s
                    example = self.convert_to_ofrecord(img_data)
                    size = example.ByteSize()
                    f.write(struct.pack("q", size))
                    f.write(example.SerializeToString())
                end = time.time()
                print(file_path + " finished, cost total {1} s".format(i, int(end - start)))

    def run(self):
        amplifier = 2 # 扩大系数，如果cut_num=1，只对应单线程，所以要放大到10以上cut_num的倍数
        while self.cut_num < 10:
            self.cut_num = self.cut_num * amplifier
            amplifier += 1
        self.process_num = self.cut_num

        P = []
        p1 = Process(target=self.convert1, args=('1', 0, int(self.cut_num / self.process_num) * 1))
        for i in range(1, self.process_num - 1):
            p = Process(target=self.convert1,
                        args=('{}'.format(i + 1), int(self.cut_num / self.process_num) * i,
                              int(self.cut_num / self.process_num) * (i + 1)))
            P.append(p)
        P.append(p1)
        # print(P)

        for process in P:
            process.start()


if __name__ == '__main__':
    convert = ConvertSplit(output_filepath='./test', cut_num=11)
    convert.run()

**Comment by ZHAIXINGZHAIYUE** [comment]
不需要手动进行数据拆分吧，分布式训练的时候，程序会自动处理的。
